# Generated by Django 4.2.19 on 2025-05-08 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('age', models.IntegerField(null=True)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=10, null=True)),
                ('goal', models.CharField(choices=[('lose_weight', 'Похудение'), ('gain_weight', 'Набор массы'), ('maintain', 'Поддержание')], max_length=15, null=True)),
                ('target_months', models.IntegerField(choices=[(1, '1 месяц'), (3, '3 месяца')], null=True)),
                ('training_level', models.CharField(choices=[('1', '1 раз'), ('2-3', '2-3 раза'), ('4-5', '4-5 раз'), ('6+', '6 и более')], default='2-3', max_length=10, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('goal_snapshot', models.CharField(blank=True, max_length=15, null=True)),
                ('age_snapshot', models.IntegerField(blank=True, null=True)),
                ('weight_snapshot', models.FloatField(blank=True, null=True)),
                ('height_snapshot', models.FloatField(blank=True, null=True)),
                ('training_level_snapshot', models.CharField(blank=True, max_length=10, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('macros', models.JSONField(blank=True, null=True)),
                ('training_recommendations', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=6)),
                ('age_category', models.CharField(choices=[('10-18', '10-18 лет'), ('19-30', '19-30 лет'), ('31-59', '31-59 лет'), ('60+', '60+ лет')], max_length=5)),
                ('goal', models.CharField(choices=[('gain_weight', 'Набор массы'), ('maintain', 'Поддержание'), ('lose_weight', 'Похудение')], max_length=12)),
                ('description', models.TextField(help_text='Описание рекомендаций')),
            ],
            options={
                'verbose_name': 'Шаблон рекомендаций',
                'verbose_name_plural': 'Шаблоны рекомендаций',
                'unique_together': {('gender', 'age_category', 'goal')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Упражнение шаблона', max_length=255)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='users.recommendationtemplate')),
            ],
            options={
                'verbose_name': 'Упражнение шаблона',
                'verbose_name_plural': 'Упражнения шаблона',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название упражнения или тренировки', max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='users.plan')),
            ],
            options={
                'verbose_name': 'Тренировка в плане',
                'verbose_name_plural': 'Тренировки в плане',
                'ordering': ['id'],
            },
        ),
    ]
